### ISSUE TITLE
ignoring message on overload

### ISSUE THREAD

**Issue by sudo-do** [nerdguyahmad/discord-chatbot#3]
This happens if there are too many messages come in
```
json.decoder.JSONDecodeError: Expecting value: line 1 column 1 (char 0)
Ignoring exception in on_message
Traceback (most recent call last):
  File "/data/data/com.termux/files/usr/lib/python3.9/site-packages/discord/client.py", line 343, in _run_event
    await coro(*args, **kwargs)
  File "/data/data/com.termux/files/home/discord-chatbot/x/discord-chatbot/discord-chatbot/main.py", line 63, in on_message
    response= await rs.get_ai_response(message.content)
  File "/data/data/com.termux/files/usr/lib/python3.9/site-packages/apiclient/core.py", line 106, in async_call
    response = post_processor(response)
  File "/data/data/com.termux/files/usr/lib/python3.9/site-packages/prsaw/PRSAW.py", line 51, in <lambda>
    self._post_processors.append(lambda res: res.json())
  File "/data/data/com.termux/files/usr/lib/python3.9/site-packages/httpx/_models.py", line 1116, in json
    return jsonlib.loads(self.text, **kwargs)
  File "/data/data/com.termux/files/usr/lib/python3.9/json/__init__.py", line 346, in loads
    return _default_decoder.decode(s)
  File "/data/data/com.termux/files/usr/lib/python3.9/json/decoder.py", line 337, in decode
    obj, end = self.raw_decode(s, idx=_w(s, 0).end())
  File "/data/data/com.termux/files/usr/lib/python3.9/json/decoder.py", line 355, in raw_decode
    raise JSONDecodeError("Expecting value", s, err.value) from None
json.decoder.JSONDecodeError: Expecting value: line 1 column 1 (char 0)
```

next message makes the bot start back, but it doesn't reply to the message makes it crash

**Comment by nerdguyahmad** [comment]
I think `get_ai_response()` returned NoneType because of so many requests.

**Comment by sudo-do** [comment]
maybe,
```
resp=None
while resp==None:
  resp=get_ai_response()
```

**Comment by nerdguyahmad** [comment]
Yeah. Maybe.

**Comment by nerdguyahmad** [comment]
@sudo-do I tried to handle this in #5

**Comment by nerdguyahmad** [comment]
Alright I'm going to close this and merge the #5 PR.
