### ISSUE TITLE
Two errors when chatting with the bot

### ISSUE THREAD

**Issue by FlamptX** [nerdguyahmad/discord-chatbot#6]
```
Ignoring exception in on_message
Traceback (most recent call last):
  File "C:\Users\PC\AppData\Local\Programs\Python\Python38\lib\site-packages\discord\client.py", line 343, in _run_event
    await coro(*args, **kwargs)
  File "C:/Users/PC/Desktop/Dino1/My code/discord-chatbot/main.py", line 51, in on_message
    if row[2] == "0":
TypeError: 'NoneType' object is not subscriptable
Command raised an exception: TypeError: object NoneType can't be used in 'await' expression
```
And
```
Traceback (most recent call last):
  File "C:\Users\PC\AppData\Local\Programs\Python\Python38\lib\site-packages\httpx\_exceptions.py", line 326, in map_exceptions
    yield
  File "C:\Users\PC\AppData\Local\Programs\Python\Python38\lib\site-packages\httpx\_client.py", line 1502, in _send_single_request
    (status_code, headers, stream, ext,) = await transport.arequest(
  File "C:\Users\PC\AppData\Local\Programs\Python\Python38\lib\site-packages\httpcore\_async\connection_pool.py", line 218, in arequest
    response = await connection.arequest(
  File "C:\Users\PC\AppData\Local\Programs\Python\Python38\lib\site-packages\httpcore\_async\connection.py", line 106, in arequest
    return await self.connection.arequest(method, url, headers, stream, ext)
  File "C:\Users\PC\AppData\Local\Programs\Python\Python38\lib\site-packages\httpcore\_async\http11.py", line 72, in arequest
    ) = await self._receive_response(timeout)
  File "C:\Users\PC\AppData\Local\Programs\Python\Python38\lib\site-packages\httpcore\_async\http11.py", line 133, in _receive_response
    event = await self._receive_event(timeout)
  File "C:\Users\PC\AppData\Local\Programs\Python\Python38\lib\site-packages\httpcore\_async\http11.py", line 172, in _receive_event
    data = await self.socket.read(self.READ_NUM_BYTES, timeout)
  File "C:\Users\PC\AppData\Local\Programs\Python\Python38\lib\site-packages\httpcore\_backends\asyncio.py", line 157, in read
    raise
  File "C:\Users\PC\AppData\Local\Programs\Python\Python38\lib\contextlib.py", line 131, in __exit__
    self.gen.throw(type, value, traceback)
  File "C:\Users\PC\AppData\Local\Programs\Python\Python38\lib\site-packages\httpcore\_exceptions.py", line 12, in map_exceptions
    raise to_exc(exc) from None
httpcore.ReadTimeout

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "C:\Users\PC\AppData\Local\Programs\Python\Python38\lib\site-packages\discord\client.py", line 343, in _run_event
    await coro(*args, **kwargs)
  File "C:/Users/PC/Desktop/Dino1/My code/discord-chatbot/main.py", line 66, in on_message
    response= await rs.get_ai_response(msg)
  File "C:\Users\PC\AppData\Local\Programs\Python\Python38\lib\site-packages\apiclient\core.py", line 104, in async_call
    response = await self.session.send(httpx_request)
  File "C:\Users\PC\AppData\Local\Programs\Python\Python38\lib\site-packages\httpx\_client.py", line 1406, in send
    response = await self._send_handling_auth(
  File "C:\Users\PC\AppData\Local\Programs\Python\Python38\lib\site-packages\httpx\_client.py", line 1444, in _send_handling_auth
    response = await self._send_handling_redirects(
  File "C:\Users\PC\AppData\Local\Programs\Python\Python38\lib\site-packages\httpx\_client.py", line 1476, in _send_handling_redirects
    response = await self._send_single_request(request, timeout)
  File "C:\Users\PC\AppData\Local\Programs\Python\Python38\lib\site-packages\httpx\_client.py", line 1502, in _send_single_request
    (status_code, headers, stream, ext,) = await transport.arequest(
  File "C:\Users\PC\AppData\Local\Programs\Python\Python38\lib\contextlib.py", line 131, in __exit__
    self.gen.throw(type, value, traceback)
  File "C:\Users\PC\AppData\Local\Programs\Python\Python38\lib\site-packages\httpx\_exceptions.py", line 343, in map_exceptions
    raise mapped_exc(message, **kwargs) from exc  # type: ignore
httpx.ReadTimeout
```

**Comment by nerdguyahmad** [comment]
The first one is probably because, I'm using the old and not so good way to fetch data from `sqlite.Cursor` object. I'll change it to `sqlite.Cursor.fetchone`.

**Comment by nerdguyahmad** [comment]
Unsure about second one.

**Comment by FlamptX** [comment]
I think that the second one happened when I asnwered with `ok`
That's when it stopped responding.

**Comment by nerdguyahmad** [comment]
Second one is probably something to do with the API.

**Comment by nerdguyahmad** [comment]
The fix for first one. 👈🏻 #8
